CREATE TABLE IF NOT EXISTS admin_users (
 id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL,
 owner INTEGER NOT NULL DEFAULT 0, permissions TEXT NOT NULL DEFAULT '[]', active INTEGER NOT NULL DEFAULT 1,
 password_hash TEXT, salt TEXT, invite_hash TEXT UNIQUE, invite_expires INTEGER,
 created_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS admin_sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES admin_users(id),expires INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS session_user ON admin_sessions(user_id);
CREATE TABLE IF NOT EXISTS admin_limits (key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admin_settings (key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_audit (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT,action TEXT NOT NULL,target TEXT,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS admin_uploads (asset_id INTEGER PRIMARY KEY,user_id TEXT NOT NULL,expires INTEGER NOT NULL);
